version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=ai.abutolib.uz,127.0.0.1,localhost
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,https://localhost:3000,https://ai.abutolib.uz,https://abutolib.uz
    networks:
      - abutolib_net
    restart: always

networks:
  abutolib_net:
    driver: bridge